################################### Nederland taal #####################################
[nl]
    languageName = "NL"
    languageCode = "nl"
    contentDir = "content/nederland"
    weight = 1
    home = "Home"
    # copyright
    copyright = "PPME Den Haag IT Division - 2022 | Based on [Educenter](https://github.com/themefisher/educenter-hugo) Hugo theme"

################################### Indonesian language #####################################
[id]
    languageName = "ID"
    languageCode = "id"
    contentDir = "content/indonesia"
    weight = 2
    home = "Home"
    # copyright
    copyright = "PPME Den Haag IT Division - 2022 | Based on [Educenter](https://github.com/themefisher/educenter-hugo) Hugo theme"




################################### English language #####################################
[en]
    languageName = "EN"
    languageCode = "en"
    contentDir = "content/english"
    weight = 3
    home = "Home"
    # copyright
    copyright = "PPME Den Haag IT Division - 2022 | Based on [Educenter](https://github.com/themefisher/educenter-hugo) Hugo theme"



