[[main]]
name = "Dakwah"
url = "dakwah/"
weight = 1

[[main]]
name = "Ibadah"
url = "ibadah/"
weight = 2

[[main]]
name = "Events"
url = "event/"
weight = 3

  
[[main]]
name = "Kontak"
url = "contact/"
weight = 4

# main menu
[[main]]
name = "Tentang Kami"
url = "about/"
weight = 5
