[[main]]
name = "Dakwah"
url = "dakwah/"
weight = 1

[[main]]
name = "Ibadah"
url = "ibadah/"
weight = 2

[[main]]
name = "Evenementen"
url = "event/"
weight = 3

  
[[main]]
name = "Kontakt"
url = "contact/"
weight = 4

# main menu
[[main]]
name = "Over Ons"
url = "about/"
weight = 5