######################## default configuration ####################
#baseURL = "https://demo.gethugothemes.com/educenter/examplesite/"
title = "PPME Den Haag"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "PPME Den Haag"
author = "PPME Den Haag IT Team"
# contact info
address = "Medlerstraat 4, 2531 HA Den Haag"
mobile = "+31-to-be-confirmed"
email = "info@ppmedenhaag.nl"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = false
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/PPMEcabDenHaag/"

#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

#[[params.social]]
#title = "github"
#icon = "ti-github" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"


################################### English language #####################################
[Languages.en]
languageName = "EN"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "PPME Den Haag IT Division - 2022 | Based on [Educenter](https://github.com/themefisher/educenter-hugo) Hugo theme"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[Languages.en.menu.main]]
name = "course"
url = "course/"
weight = 2

[[Languages.en.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event/"



  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research/"
  
[[Languages.en.menu.main]]
name = "blog"
url = "blog/"
weight = 4
  
[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher/"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.en.menu.footer]]
name = "event"
url = "event/"

[[Languages.en.menu.footer]]
name = "dakwah"
url = "dakwah/"



[[Languages.en.menu.footer]]
name = "research"
url = "research/"

################################### Indonesian language #####################################
[Languages.id]
languageName = "ID"
languageCode = "id"
contentDir = "content/indonesia"
weight = 1
home = "Home"
# copyright
copyright = "PPME Den Haag IT Division - 2022 | Based on [Educenter](https://github.com/themefisher/educenter-hugo) Hugo theme"



################### Indonesia navigation ####################

# main menu
[[Languages.id.menu.main]]
name = "About"
url = "about/"
weight = 1

[[Languages.id.menu.main]]
name = "course"
url = "course/"
weight = 2

[[Languages.id.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.id.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher/"

  [[Languages.id.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"

  [[Languages.id.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event/"



  [[Languages.id.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research/"
  
[[Languages.id.menu.main]]
name = "blog"
url = "blog/"
weight = 4
  
[[Languages.id.menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[Languages.id.menu.footer]]
name = "teacher"
url = "teacher/"

[[Languages.id.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.id.menu.footer]]
name = "event"
url = "event/"



[[Languages.id.menu.footer]]
name = "research"
url = "research/"






################################### Nederland taal #####################################
[Languages.nl]
languageName = "NL"
languageCode = "nl"
contentDir = "content/nederland"
weight = 1
home = "Home"
# copyright
copyright = "PPME Den Haag IT Division - 2022 | Based on [Educenter](https://github.com/themefisher/educenter-hugo) Hugo theme"



################### Nederland navigation ####################

# main menu
[[Languages.nl.menu.main]]
name = "About"
url = "about/"
weight = 1

[[Languages.nl.menu.main]]
name = "course"
url = "course/"
weight = 2

[[Languages.nl.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.nl.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher/"

  [[Languages.nl.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"

  [[Languages.nl.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event/"



  [[Languages.nl.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research/"
  
[[Languages.nl.menu.main]]
name = "blog"
url = "blog/"
weight = 4
  
[[Languages.nl.menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[Languages.nl.menu.footer]]
name = "teacher"
url = "teacher/"

[[Languages.nl.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.nl.menu.footer]]
name = "event"
url = "event/"


[[Languages.nl.menu.footer]]
name = "research"
url = "research/"
